SELECT * FROM TABELA_PRODUTOS WHERE PRODUTO = "544931";

SELECT * FROM TABELA_CLIENTES WHERE CIDADE = "Rio de Janeiro";

UPDATE TABELA_PRODUTOS SET SABOR = "Cítricos" WHERE SABOR = "Limão";

SELECT * FROM TABELA_PRODUTOS WHERE SABOR = "Cítricos";

SELECT * FROM TABELA_VENDEDORES WHERE NOME = 'Claudia Moraes';



SELECT * FROM TABELA_CLIENTES WHERE IDADE = 22;
SELECT * FROM TABELA_CLIENTES WHERE IDADE > 22;
SELECT * FROM TABELA_CLIENTES WHERE IDADE >= 22;
SELECT * FROM TABELA_CLIENTES WHERE IDADE <> 22;
SELECT * FROM TABELA_CLIENTES WHERE NOME >= "Fernando Cavalcante"; /*EXIBE AS STRINGS EM ORDEM ALFABETICA*/



/*MY SQL NÃO CONSEGUE TRAZER O VALOR EXATO DO TIPO FLOAT, JÁ DECIMAL SIM.*/

SELECT * FROM TABELA_PRODUTOS WHERE PRECO_LISTA = 16.008;/*NÃO FUNCIONA*/
SELECT * FROM TABELA_PRODUTOS WHERE PRECO_LISTA < 16.008;
SELECT * FROM TABELA_PRODUTOS WHERE PRECO_LISTA > 16.008;
SELECT * FROM TABELA_PRODUTOS WHERE PRECO_LISTA <> 16.008;/*O VALOR COM 16.008 AINDA SERÁ EXIBIDO*/

SELECT * FROM TABELA_PRODUTOS WHERE PRECO_LISTA BETWEEN 16.007 AND 16.009;/*IRA EXIBIR O VALOR 16.008 NO MYSQL*/
SELECT * FROM TABELA_PRODUTOS WHERE PRECO_LISTA >= 16.007 AND PRECO_LISTA <= 16.009;/*TAMBEM IRA EXIBIR O VALOR 16.008 NO MYSQL*/




SELECT MATRICULA, NOME FROM TABELA_VENDEDORES WHERE PERCENTUAL_COMISSAO > 0.10;
SELECT MATRICULA, PERCENTUAL_COMISSAO, NOME FROM TABELA_VENDEDORES;



/*FILTRANDO DATAS*/
SELECT * FROM TABELA_CLIENTES WHERE DATA_NASCIMENTO = "1995-01-13";
SELECT * FROM TABELA_CLIENTES WHERE DATA_NASCIMENTO > "1995-01-13";
SELECT * FROM TABELA_CLIENTES WHERE DATA_NASCIMENTO <= "1995-01-13";

SELECT * FROM TABELA_CLIENTES WHERE YEAR(DATA_NASCIMENTO) = "1995";
SELECT * FROM TABELA_CLIENTES WHERE MONTH(DATA_NASCIMENTO) = "10";



/*FILTROS COMPOSTOS*/
SELECT * FROM TABELA_PRODUTOS WHERE PRECO_LISTA >= 16.007 AND PRECO_LISTA <= 16.009;

SELECT * FROM TABELA_CLIENTES WHERE IDADE >= 18 AND IDADE <= 22 AND SEXO = "F";

SELECT * FROM TABELA_CLIENTES WHERE CIDADE = "Rio de Janeiro" OR BAIRRO = "JARDINS";