USE SUCOS;

ALTER TABLE TABELA_PRODUTOS ADD PRIMARY KEY (PRODUTO);

INSERT INTO TABELA_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
    VALUES ('104017', 'Light - 350ml - Melância', 'Lata', '350ml', 'Melância', 4.56);
    
ALTER TABLE TABELA_CLIENTES ADD PRIMARY KEY (CPF);
ALTER TABLE TABELA_CLIENTES ADD COLUMN (DATA_NASCIMENTO DATE);
    
SELECT * FROM TABELA_PRODUTOS;
    