/*CRIANDO TABELAS*/
CREATE TABLE TABELA_CLIENTES(
	CPF VARCHAR(11),
	NOME VARCHAR(100),
	ENDERECO1 VARCHAR(150),
	ENDERECO2 VARCHAR(150),
	BAIRRO VARCHAR(50),
	CIDADE VARCHAR(50),
	ESTADO VARCHAR(50),
	CEP VARCHAR(8),
	IDADE SMALLINT,
	SEXO VARCHAR(1),
	LIMITE_CREDITO FLOAT,
	VOLUME_COMPRA FLOAT,
	PRIMEIRA_COMPRA BIT(1)
);


CREATE TABLE TABELA_VENDEDORES (
	MATRICULA VARCHAR(5),
    NOME VARCHAR(100),
    PERCENTURAL_COMISSAO FLOAT
);


CREATE TABLE TABELA_PRODUTOS (
	PRODUTO VARCHAR(20),
    NOME VARCHAR(150),
    EMBALAGEM VARCHAR(50),
    TAMANHO VARCHAR(50),
    SABOR VARCHAR(50),
    PRECO_LISTA FLOAT
);



/*APAGANDO TABELAS*/
DROP TABLE tabela_vendedores2;






