INSERT INTO TABELA_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
    VALUES ('104017', 'Light - 350ml - Melância', 'Lata', '350ml', 'Melância', 4.56);
    
INSERT INTO TABELA_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
	VALUES ('1037797', 'Clean - 2litros - Laranja', 'PET', '2 Litros', 'Laranja', 16.01);

INSERT INTO TABELA_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
	VALUES ('9947820', 'Banana Flask - 400ml - Banana', 'Garraga', '400ml', 'Banana', 8.00);

INSERT INTO TABELA_VENDEDORES (MATRICULA, NOME, PERCENTUAL_COMISSAO) VALUES ('00233', 'João Geraldo da Fonseca', 10);
INSERT INTO TABELA_VENDEDORES (MATRICULA, NOME, PERCENTUAL_COMISSAO) VALUES ('00235', 'Márcio Almeida da Silva', 0.08);
INSERT INTO TABELA_VENDEDORES (MATRICULA, NOME, PERCENTUAL_COMISSAO) VALUES ('00236', 'Claudia Moraes', 0.10);


INSERT INTO TABELA_CLIENTES (
CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP, IDADE, SEXO, 
LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA, DATA_NASCIMENTO)
VALUES ('00388934505','João da Silva','Rua projetada A número 10','',
'VILA ROMAN', 'CARATINGA', 'AMAZONAS','2222222',30,'M', 10000.00, 2000,
0, '1989-10-05');

    
SELECT * FROM TABELA_PRODUTOS;
SELECT * FROM TABELA_VENDEDORES;