USE SUCOS;

SELECT * FROM TABELA_CLIENTES;

SELECT CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP,
DATA_NASCIMENTO, IDADE, SEXO, LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA
FROM TABELA_CLIENTES;

SELECT CPF, NOME FROM TABELA_CLIENTES;

SELECT CPF, NOME FROM TABELA_CLIENTES LIMIT 5;

SELECT CPF AS CPF_CLIENTE, NOME AS NOME_CLIENTE FROM TABELA_CLIENTES;

SELECT NOME, CPF, SEXO, IDADE, DATA_NASCIMENTO FROM TABELA_CLIENTES;

SELECT NOME, MATRICULA FROM TABELA_VENDEDORES;